version: '3'
services:
  db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:6.0-rc1-alpine
    expose:
      - "5672"
  django:
    build: .
    command: >
      sh -c "cd evalmgr &&
             python manage.py collectstatic --noinput &&
             python manage.py makemigrations --noinput &&
             python manage.py migrate --noinput &&
             gunicorn --reload evalmgr.wsgi:application -b 0.0.0.0:8001 --error-logfile gunicorn.error"
    restart: "no"
    volumes:
      - .:/opt/services/djangoapp/src
      - static_volume:/opt/services/djangoapp/src/evalmgr/static  # <-- bind the static volume
      - media_volume:/opt/services/djangoapp/src/evalmgr/media  # <-- bind the media volume
    depends_on:
      - db
      - redis
  celery:
    build: .
    command: >
      sh -c "cd evalmgr && celery -A evalmgr worker -l info"
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
      - django
    links:
      - redis
  nginx:
    image: nginx:latest
    ports:
     - 80:80
    volumes:
     - ./config/nginx/conf.d:/etc/nginx/conf.d
     - static_volume:/opt/services/djangoapp/src/evalmgr/static  # <-- bind the static volume
     - media_volume:/opt/services/djangoapp/src/evalmgr/media  # <-- bind the media volume
    depends_on:
     - django
volumes:
  postgres_data:
  static_volume:
  media_volume:
