version: '3'
services:
  db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:6.0-rc1-alpine
  django:
    build: .
    command: "cd evalmgr &&
             python manage.py collectstatic &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             gunicorn --reload evalmgr.wsgi:application -b 0.0.0.0:8000"
    restart: on-failure
    volumes:
      - media_volume:/code/automated-assignment-evaluation/evalmggr/media
    depends_on:
      - db
      - redis
  celery:
    build: .
    command: "cd evalmgr && celery -A evalmgr worker -l info"
    depends_on:
      - db
      - redis
      - django
  nginx:
    image: nginx:latest
    ports:
     - 80:80
    volumes:
     - ./config/nginx/conf.d:/etc/nginx/conf.d
     - media_volume:/opt/services/djangoapp/src/evalmgr/media 
    depends_on:
     - django
volumes:
  postgres_data:
  media_volume:
