---
test_name: Add user

stages:
  - name: Add a user
    request:
      url: http://localhost:5000/api/v1/users
      method: PUT
      json:
        username: "test1"
        password: "1234567890123456789012345678901234567890"
    response:
      status_code: 201

  - name: User exists
    request:
      url: http://localhost:5000/api/v1/users
      method: PUT
      json:
        username: "test1"
        password: "1234567890123456789012345678901234567890"
    response:
      status_code: 400

  - name: User doesn't exist, password is invalid
    request:
      url: http://localhost:5000/api/v1/users
      method: PUT
      json:
        username: "test2"
        password: "1234567890"
    response:
      status_code: 400

  - name: Wrong method
    request:
      url: http://localhost:5000/api/v1/users
      method: POST
      json:
        username: "test2"
        password: "1234567890123456789012345678901234567890"
    response:
      status_code: 405

---
test_name: Delete user

stages:
  - name: Add user to delete
    request:
      url: http://localhost:5000/api/v1/users
      method: PUT
      json:
        username: "test0"
        password: "1234567890123456789012345678901234567890"
    response:
      status_code: 201

  - name: Wrong Method
    request:
      url: http://localhost:5000/api/v1/users/test0
      method: POST
    response:
      status_code: 405

  - name: User exists
    request:
      url: http://localhost:5000/api/v1/users/test0
      method: DELETE
    response:
      status_code: 200

  - name: User doesn't exist
    request:
      url: http://localhost:5000/api/v1/users/test0
      method: DELETE
    response:
      status_code: 400

---
test_name: Create a new ride

stages:
  - name: Add user to create ride
    request:
      url: http://localhost:5000/api/v1/users
      method: PUT
      json:
        username: "test0"
        password: "1234567890123456789012345678901234567890"
    response:
      status_code: 201

  - name: User exists, locations are ok
    request:
      url: http://localhost:5000/api/v1/rides
      method: POST
      json:
        created_by: "test0"
        timestamp: "18-07-2020:00-24-10"
        source: "174"
        destination: "175"
    response:
      status_code: 201

  - name: User doesn't exist
    request:
      url: http://localhost:5000/api/v1/rides
      method: POST
      json:
        created_by: "test1"
        timestamp: "18-07-2020:00-24-10"
        source: "174"
        destination: "175"
    response:
      status_code: 400

  - name: User exists, locations are invalid
    request:
      url: http://localhost:5000/api/v1/rides
      method: POST
      json:
        created_by: "test0"
        timestamp: "18-07-2020:00-24-10"
        source: "174"
        destination: "1750"
    response:
      status_code: 400

  - name: Wrong Method
    request:
      url: http://localhost:5000/api/v1/rides
      method: PUT
      json:
        created_by: "test0"
        timestamp: "18-07-2020:00-24-10"
        source: "174"
        destination: "175"
    response:
      status_code: 405

---
test_name: List all upcoming rides for a given source and destination

stages:
  - name: Add user to create ride
    request:
      url: http://localhost:5000/api/v1/users
      method: PUT
      json:
        username: "test0"
        password: "1234567890123456789012345678901234567890"
    response:
      status_code: 201

  - name: Create a ride
    request:
      url: http://localhost:5000/api/v1/rides
      method: POST
      json:
        created_by: "test0"
        timestamp: "18-07-2020:00-24-10"
        source: "174"
        destination: "175"
    response:
      status_code: 201

  - name: Create another ride
    request:
      url: http://localhost:5000/api/v1/rides
      method: POST
      json:
        created_by: "test0"
        timestamp: "18-07-2019:00-24-10"
        source: "174"
        destination: "175"
    response:
      status_code: 201

  - name: Locations are ok, rides exist
    request:
      url: http://localhost:5000/api/v1/rides
      method: GET
      params:
        source: "174"
        destination: "175"
    response:
      status_code: 200

  - name: Locations are ok, no rides
    request:
      url: http://localhost:5000/api/v1/rides
      method: GET
      params:
        source: "14"
        destination: "15"
    response:
      status_code: 204

  - name: Locations are invalid
    request:
      url: http://localhost:5000/api/v1/rides
      method: GET
      params:
        source: "14"
        destination: "1500"
    response:
      status_code: 400

  - name: Wrong Method
    request:
      url: http://localhost:5000/api/v1/rides
      method: PUT
      params:
        source: "174"
        destination: "175"
    response:
      status_code: 405

---
test_name: List all the details of a given ride

stages:
  - name: Add user to create ride
    request:
      url: http://localhost:5000/api/v1/users
      method: PUT
      json:
        username: "test0"
        password: "1234567890123456789012345678901234567890"
    response:
      status_code: 201

  - name: Create a ride
    request:
      url: http://localhost:5000/api/v1/rides
      method: POST
      json:
        created_by: "test0"
        timestamp: "18-07-2020:00-24-10"
        source: "174"
        destination: "175"
    response:
      status_code: 201

  - name: Ride id is ok
    request:
      url: http://localhost:5000/api/v1/rides/1
      method: GET
    response:
      status_code: 200

  - name: Ride id is invalid
    request:
      url: http://localhost:5000/api/v1/rides/2
      method: GET
    response:
      status_code: 204

  - name: Wrong Method
    request:
      url: http://localhost:5000/api/v1/rides/1
      method: PUT
    response:
      status_code: 405

---
test_name: Join an existing ride

stages:
  - name: Add user to create ride
    request:
      url: http://localhost:5000/api/v1/users
      method: PUT
      json:
        username: "test0"
        password: "1234567890123456789012345678901234567890"
    response:
      status_code: 201

  - name: Another user to join ride
    request:
      url: http://localhost:5000/api/v1/users
      method: PUT
      json:
        username: "test1"
        password: "1234567890123456789012345678901234567890"
    response:
      status_code: 201

  - name: Create a ride
    request:
      url: http://localhost:5000/api/v1/rides
      method: POST
      json:
        created_by: "test0"
        timestamp: "18-07-2020:00-24-10"
        source: "174"
        destination: "175"
    response:
      status_code: 201

  - name: Ride id is invalid
    request:
      url: http://localhost:5000/api/v1/rides/2
      method: POST
      json:
        username: "test1"
    response:
      status_code: 400

  - name: Username is invalid
    request:
      url: http://localhost:5000/api/v1/rides/1
      method: POST
      json:
        username: "test2"
    response:
      status_code: 400

  - name: Username is creator
    request:
      url: http://localhost:5000/api/v1/rides/1
      method: POST
      json:
        username: "test0"
    response:
      status_code: 400

  - name: Ride id is ok, username is ok
    request:
      url: http://localhost:5000/api/v1/rides/1
      method: POST
      json:
        username: "test1"
    response:
      status_code: 200

  - name: Rider exists
    request:
      url: http://localhost:5000/api/v1/rides/1
      method: POST
      json:
        username: "test1"
    response:
      status_code: 400

  - name: Wrong Method
    request:
      url: http://localhost:5000/api/v1/rides/1
      method: PUT
      json:
        username: "test1"
    response:
      status_code: 405

---
test_name: Delete ride

stages:
  - name: Add user to create ride
    request:
      url: http://localhost:5000/api/v1/users
      method: PUT
      json:
        username: "test0"
        password: "1234567890123456789012345678901234567890"
    response:
      status_code: 201

  - name: Create a ride
    request:
      url: http://localhost:5000/api/v1/rides
      method: POST
      json:
        created_by: "test0"
        timestamp: "18-07-2020:00-24-10"
        source: "174"
        destination: "175"
    response:
      status_code: 201

  - name: Ride id is valid
    request:
      url: http://localhost:5000/api/v1/rides/1
      method: DELETE
    response:
      status_code: 200

  - name: Ride id is invalid
    request:
      url: http://localhost:5000/api/v1/rides/1
      method: DELETE
    response:
      status_code: 400

  - name: Wrong Method
    request:
      url: http://localhost:5000/api/v1/rides/1
      method: PUT
    response:
      status_code: 405
